#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.

echo triggered postmkvirtualenv script

create_venv_symlink(){
    echo $VIRTUAL_ENV
    if [ -d $VIRTUAL_ENV ];
    then
    	echo creating symlink to virtualenvwrapper environemnt

    	ln -s $VIRTUAL_ENV venv

    	echo 'ln -s' $VIRTUAL_ENV venv
    fi
}

create_venv_symlink
